// Code generated by middleware generator version "test" DO NOT EDIT.

package interfacesmw

import (
	"context"

	"github.com/Makpoc/gomigen/test/integration/testdata/tabletests/interfaces"
	"github.com/Makpoc/gomigen/types"
)

type ChanInArgAndReturnMiddleware struct {
	next interfaces.ChanInArgAndReturn
	hook types.Hook
}

// if this check fails middleware needs to be re-generated.
var _ interfaces.ChanInArgAndReturn = (*ChanInArgAndReturnMiddleware)(nil)

func NewChanInArgAndReturnMiddleware(
	next interfaces.ChanInArgAndReturn,
	hook types.Hook,
) *ChanInArgAndReturnMiddleware {
	return &ChanInArgAndReturnMiddleware{
		next: next,
		hook: hook,
	}
}

func (mw *ChanInArgAndReturnMiddleware) Process(arg0 chan struct{}, arg1 chan<- string) <-chan error {
	methodInfo := types.MethodInfo{
		Package:   "github.com/Makpoc/gomigen/test/integration/testdata/tabletests/interfaces",
		Interface: "ChanInArgAndReturn",
		Method:    "Process",
	}

	ctx := context.Background()

	ctx = mw.hook.OnEntry(ctx, methodInfo)
	res0 := mw.next.Process(arg0, arg1)
	mw.hook.OnExit(ctx, methodInfo, nil)
	return res0
}
