// Code generated by middleware generator version "test" DO NOT EDIT.

package interfacesmw

import (
	"context"

	"github.com/Makpoc/gomigen/test/integration/testdata/tabletests/interfaces"
	"github.com/Makpoc/gomigen/types"
)

type ContextFirstArgumentMiddleware struct {
	next interfaces.ContextFirstArgument
	hook types.Hook
}

// if this check fails middleware needs to be re-generated.
var _ interfaces.ContextFirstArgument = (*ContextFirstArgumentMiddleware)(nil)

func NewContextFirstArgumentMiddleware(
	next interfaces.ContextFirstArgument,
	hook types.Hook,
) *ContextFirstArgumentMiddleware {
	return &ContextFirstArgumentMiddleware{
		next: next,
		hook: hook,
	}
}

func (mw *ContextFirstArgumentMiddleware) Process(arg0 context.Context, arg1 int) {
	methodInfo := types.MethodInfo{
		Package:   "github.com/Makpoc/gomigen/test/integration/testdata/tabletests/interfaces",
		Interface: "ContextFirstArgument",
		Method:    "Process",
		Params:    []interface{}{arg0, arg1},
	}

	ctx := arg0

	ctx = mw.hook.OnEntry(ctx, methodInfo)
	mw.next.Process(ctx, arg1)
	mw.hook.OnExit(ctx, methodInfo, nil)
}
