// Code generated by middleware generator version "test" DO NOT EDIT.

package interfacesmw

import (
	"context"

	"github.com/Makpoc/gomigen/test/integration/testdata/tabletests/interfaces"
	"github.com/Makpoc/gomigen/types"
)

type CustomInterfaceInArgAndReturnMiddleware struct {
	next interfaces.CustomInterfaceInArgAndReturn
	hook types.Hook
}

// if this check fails middleware needs to be re-generated.
var _ interfaces.CustomInterfaceInArgAndReturn = (*CustomInterfaceInArgAndReturnMiddleware)(nil)

func NewCustomInterfaceInArgAndReturnMiddleware(
	next interfaces.CustomInterfaceInArgAndReturn,
	hook types.Hook,
) *CustomInterfaceInArgAndReturnMiddleware {
	return &CustomInterfaceInArgAndReturnMiddleware{
		next: next,
		hook: hook,
	}
}

func (mw *CustomInterfaceInArgAndReturnMiddleware) Process(arg0 interfaces.ContextFirstArgumentReturnsError) interfaces.ReturnsMultipleValuesNoError {
	methodInfo := types.MethodInfo{
		Package:   "github.com/Makpoc/gomigen/test/integration/testdata/tabletests/interfaces",
		Interface: "CustomInterfaceInArgAndReturn",
		Method:    "Process",
	}

	ctx := context.Background()

	ctx = mw.hook.OnEntry(ctx, methodInfo)
	res0 := mw.next.Process(arg0)
	mw.hook.OnExit(ctx, methodInfo, nil)
	return res0
}
