// Code generated by middleware generator version "test" DO NOT EDIT.

package interfacesmw

import (
	"context"

	"github.com/Makpoc/gomigen/test/integration/testdata/tabletests/interfaces"
	"github.com/Makpoc/gomigen/types"
)

type EmbedAnonymousInterfaceMiddleware struct {
	next interfaces.EmbedAnonymousInterface
	hook types.Hook
}

// if this check fails middleware needs to be re-generated.
var _ interfaces.EmbedAnonymousInterface = (*EmbedAnonymousInterfaceMiddleware)(nil)

func NewEmbedAnonymousInterfaceMiddleware(
	next interfaces.EmbedAnonymousInterface,
	hook types.Hook,
) *EmbedAnonymousInterfaceMiddleware {
	return &EmbedAnonymousInterfaceMiddleware{
		next: next,
		hook: hook,
	}
}

func (mw *EmbedAnonymousInterfaceMiddleware) Do(arg0 string) error {
	methodInfo := types.MethodInfo{
		Package:   "github.com/Makpoc/gomigen/test/integration/testdata/tabletests/interfaces",
		Interface: "EmbedAnonymousInterface",
		Method:    "Do",
	}

	ctx := context.Background()

	ctx = mw.hook.OnEntry(ctx, methodInfo)
	res0 := mw.next.Do(arg0)
	mw.hook.OnExit(ctx, methodInfo, res0)
	return res0
}
