// Code generated by middleware generator version "test" DO NOT EDIT.

package interfacesmw

import (
	"context"

	"github.com/Makpoc/gomigen/test/integration/testdata/tabletests/interfaces"
	"github.com/Makpoc/gomigen/types"
)

type EmbedStandardInterfaceMiddleware struct {
	next interfaces.EmbedStandardInterface
	hook types.Hook
}

// if this check fails middleware needs to be re-generated.
var _ interfaces.EmbedStandardInterface = (*EmbedStandardInterfaceMiddleware)(nil)

func NewEmbedStandardInterfaceMiddleware(
	next interfaces.EmbedStandardInterface,
	hook types.Hook,
) *EmbedStandardInterfaceMiddleware {
	return &EmbedStandardInterfaceMiddleware{
		next: next,
		hook: hook,
	}
}

func (mw *EmbedStandardInterfaceMiddleware) Write(arg0 /* p */ []byte) (int /* n */, error /* err */) {
	methodInfo := types.MethodInfo{
		Package:   "github.com/Makpoc/gomigen/test/integration/testdata/tabletests/interfaces",
		Interface: "EmbedStandardInterface",
		Method:    "Write",
	}

	ctx := context.Background()

	ctx = mw.hook.OnEntry(ctx, methodInfo)
	res0, res1 := mw.next.Write(arg0)
	mw.hook.OnExit(ctx, methodInfo, res1)
	return res0, res1
}
