// Code generated by middleware generator version "test" DO NOT EDIT.

package interfacesmw

import (
	"context"

	"github.com/Makpoc/gomigen/test/integration/testdata/tabletests/interfaces"
	"github.com/Makpoc/gomigen/types"
)

type EmbeddedInterfaceMiddleware struct {
	next interfaces.EmbeddedInterface
	hook types.Hook
}

// if this check fails middleware needs to be re-generated.
var _ interfaces.EmbeddedInterface = (*EmbeddedInterfaceMiddleware)(nil)

func NewEmbeddedInterfaceMiddleware(
	next interfaces.EmbeddedInterface,
	hook types.Hook,
) *EmbeddedInterfaceMiddleware {
	return &EmbeddedInterfaceMiddleware{
		next: next,
		hook: hook,
	}
}

func (mw *EmbeddedInterfaceMiddleware) Process(arg0 context.Context, arg1 int) (int, error) {
	methodInfo := types.MethodInfo{
		Package:   "github.com/Makpoc/gomigen/test/integration/testdata/tabletests/interfaces",
		Interface: "EmbeddedInterface",
		Method:    "Process",
		Params:    []interface{}{arg0, arg1},
	}

	ctx := arg0

	ctx = mw.hook.OnEntry(ctx, methodInfo)
	res0, res1 := mw.next.Process(ctx, arg1)
	mw.hook.OnExit(ctx, methodInfo, res1)
	return res0, res1
}
