// Code generated by middleware generator version "test" DO NOT EDIT.

package interfacesmw

import (
	"context"

	"github.com/Makpoc/gomigen/test/integration/testdata/tabletests/interfaces"
	"github.com/Makpoc/gomigen/types"
)

type ExtendsAnotherInterfaceMiddleware struct {
	next interfaces.ExtendsAnotherInterface
	hook types.Hook
}

// if this check fails middleware needs to be re-generated.
var _ interfaces.ExtendsAnotherInterface = (*ExtendsAnotherInterfaceMiddleware)(nil)

func NewExtendsAnotherInterfaceMiddleware(
	next interfaces.ExtendsAnotherInterface,
	hook types.Hook,
) *ExtendsAnotherInterfaceMiddleware {
	return &ExtendsAnotherInterfaceMiddleware{
		next: next,
		hook: hook,
	}
}

func (mw *ExtendsAnotherInterfaceMiddleware) Close() error {
	methodInfo := types.MethodInfo{
		Package:   "github.com/Makpoc/gomigen/test/integration/testdata/tabletests/interfaces",
		Interface: "ExtendsAnotherInterface",
		Method:    "Close",
		Params:    nil,
	}

	ctx := context.Background()

	ctx = mw.hook.OnEntry(ctx, methodInfo)
	res0 := mw.next.Close()
	mw.hook.OnExit(ctx, methodInfo, res0)
	return res0
}
func (mw *ExtendsAnotherInterfaceMiddleware) Write(arg0 /* p */ []byte) (int /* n */, error /* err */) {
	methodInfo := types.MethodInfo{
		Package:   "github.com/Makpoc/gomigen/test/integration/testdata/tabletests/interfaces",
		Interface: "ExtendsAnotherInterface",
		Method:    "Write",
		Params:    []interface{}{arg0},
	}

	ctx := context.Background()

	ctx = mw.hook.OnEntry(ctx, methodInfo)
	res0, res1 := mw.next.Write(arg0)
	mw.hook.OnExit(ctx, methodInfo, res1)
	return res0, res1
}
