// Code generated by middleware generator version "test" DO NOT EDIT.

package interfacesmw

import (
	"context"

	"github.com/Makpoc/gomigen/test/integration/testdata/tabletests/interfaces"
	"github.com/Makpoc/gomigen/test/integration/testdata/tabletests/interfaces/inner"
	"github.com/Makpoc/gomigen/types"
)

type InnerPackageReferenceMiddleware struct {
	next interfaces.InnerPackageReference
	hook types.Hook
}

// if this check fails middleware needs to be re-generated.
var _ interfaces.InnerPackageReference = (*InnerPackageReferenceMiddleware)(nil)

func NewInnerPackageReferenceMiddleware(
	next interfaces.InnerPackageReference,
	hook types.Hook,
) *InnerPackageReferenceMiddleware {
	return &InnerPackageReferenceMiddleware{
		next: next,
		hook: hook,
	}
}

func (mw *InnerPackageReferenceMiddleware) Process(arg0 inner.PackageInterface) inner.PackageInterface {
	methodInfo := types.MethodInfo{
		Package:   "github.com/Makpoc/gomigen/test/integration/testdata/tabletests/interfaces",
		Interface: "InnerPackageReference",
		Method:    "Process",
		Params:    []interface{}{arg0},
	}

	ctx := context.Background()

	ctx = mw.hook.OnEntry(ctx, methodInfo)
	res0 := mw.next.Process(arg0)
	mw.hook.OnExit(ctx, methodInfo, nil)
	return res0
}
