// Code generated by middleware generator version "test" DO NOT EDIT.

package interfacesmw

import (
	"context"

	"github.com/Makpoc/gomigen/test/integration/testdata/tabletests/interfaces"
	"github.com/Makpoc/gomigen/types"
)

type ReturnsSingleErrorMiddleware struct {
	next interfaces.ReturnsSingleError
	hook types.Hook
}

// if this check fails middleware needs to be re-generated.
var _ interfaces.ReturnsSingleError = (*ReturnsSingleErrorMiddleware)(nil)

func NewReturnsSingleErrorMiddleware(
	next interfaces.ReturnsSingleError,
	hook types.Hook,
) *ReturnsSingleErrorMiddleware {
	return &ReturnsSingleErrorMiddleware{
		next: next,
		hook: hook,
	}
}

func (mw *ReturnsSingleErrorMiddleware) Process(arg0 int) error {
	methodInfo := types.MethodInfo{
		Package:   "github.com/Makpoc/gomigen/test/integration/testdata/tabletests/interfaces",
		Interface: "ReturnsSingleError",
		Method:    "Process",
		Params:    []interface{}{arg0},
	}

	ctx := context.Background()

	ctx = mw.hook.OnEntry(ctx, methodInfo)
	res0 := mw.next.Process(arg0)
	mw.hook.OnExit(ctx, methodInfo, res0)
	return res0
}
