// Code generated by middleware generator version "test" DO NOT EDIT.

package interfacesmw

import (
	"context"

	"github.com/Makpoc/gomigen/test/integration/testdata/tabletests/interfaces"
	"github.com/Makpoc/gomigen/types"
)

type SingleMethodNoArgsNoReturnsMiddleware struct {
	next interfaces.SingleMethodNoArgsNoReturns
	hook types.Hook
}

// if this check fails middleware needs to be re-generated.
var _ interfaces.SingleMethodNoArgsNoReturns = (*SingleMethodNoArgsNoReturnsMiddleware)(nil)

func NewSingleMethodNoArgsNoReturnsMiddleware(
	next interfaces.SingleMethodNoArgsNoReturns,
	hook types.Hook,
) *SingleMethodNoArgsNoReturnsMiddleware {
	return &SingleMethodNoArgsNoReturnsMiddleware{
		next: next,
		hook: hook,
	}
}

func (mw *SingleMethodNoArgsNoReturnsMiddleware) Process() {
	methodInfo := types.MethodInfo{
		Package:   "github.com/Makpoc/gomigen/test/integration/testdata/tabletests/interfaces",
		Interface: "SingleMethodNoArgsNoReturns",
		Method:    "Process",
		Params:    nil,
	}

	ctx := context.Background()

	ctx = mw.hook.OnEntry(ctx, methodInfo)
	mw.next.Process()
	mw.hook.OnExit(ctx, methodInfo, nil)
}
