// Code generated by middleware generator version "test" DO NOT EDIT.

package interfacesmw

import (
	"context"

	"github.com/Makpoc/gomigen/test/integration/testdata/tabletests/interfaces"
	"github.com/Makpoc/gomigen/types"
)

type VariadicArgumentMiddleware struct {
	next interfaces.VariadicArgument
	hook types.Hook
}

// if this check fails middleware needs to be re-generated.
var _ interfaces.VariadicArgument = (*VariadicArgumentMiddleware)(nil)

func NewVariadicArgumentMiddleware(
	next interfaces.VariadicArgument,
	hook types.Hook,
) *VariadicArgumentMiddleware {
	return &VariadicArgumentMiddleware{
		next: next,
		hook: hook,
	}
}

func (mw *VariadicArgumentMiddleware) Process(arg0 string, arg1 ...int) {
	methodInfo := types.MethodInfo{
		Package:   "github.com/Makpoc/gomigen/test/integration/testdata/tabletests/interfaces",
		Interface: "VariadicArgument",
		Method:    "Process",
		Params:    []interface{}{arg0, arg1},
	}

	ctx := context.Background()

	ctx = mw.hook.OnEntry(ctx, methodInfo)
	mw.next.Process(arg0, arg1...)
	mw.hook.OnExit(ctx, methodInfo, nil)
}
